<?php

namespace SiteBundle\Repository;

/**
 * ShitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShitRepository extends \Doctrine\ORM\EntityRepository
{
}
