<?php

namespace Imperiv\Bundle\GalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryPageRepository extends EntityRepository
{
}
