services:
    sonata.admin.orders:
        class: LandingBundle\Admin\OrderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Order, label: Orders }
        arguments: [null, LandingBundle\Entity\Order, null]

    sonata.admin.order_items:
            class: LandingBundle\Admin\OrderItemAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: Order, label: Orders }
            arguments: [null, LandingBundle\Entity\OrderItem, null]