services:
    sonata.admin.video:
        class: SiteBundle\Admin\VideoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Videos" }
        arguments:
            - ~
            - SiteBundle\Entity\Video
            - ~
    sonata.admin.gallery_page:
        class: SiteBundle\Admin\GalleryPageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Gallery pages" }
        arguments:
            - ~
            - SiteBundle\Entity\GalleryPage
            - ~

    sonata.admin.slide:
        class: SiteBundle\Admin\SlideAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Gallery page slides" }
        arguments:
            - ~
            - SiteBundle\Entity\Slide
            - ~