services:
    SiteBundle\Controller\CRUDController:
      public: true
      autoconfigure: true

    app.gallery.unserialize_filter:
      class: SiteBundle\Twig\UnserializeExtension
      public: false
      tags:
        - { name: twig.extension }

    admin_success_handler:
      public: true
      class: SiteBundle\Services\AuthenticationHandler
      arguments: [ '@service_container' ]

    app.mailgun_service:
        class: SiteBundle\Services\MailgunService
        public: true
        autoconfigure: true
        arguments: ['%mailgun.key%', '%mailgun.endpoint%', '%mailgun.domain%', '%mailer_user%']

    SiteBundle\Services\ReCaptchaService:
      public: true
      autoconfigure: true
      arguments: ['%google_recaptcha_secret_key%']