services:
    sonata.admin.orders:
        class: Application\LandingBundle\Admin\OrderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Order, label: Orders }
        arguments: [null, Application\LandingBundle\Entity\Order, ApplicationLandingBundle:CRUD]