services:
    sonata.admin.orders.base:
        class: Application\LandingBundle\Admin\OrderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Orders" }
        arguments:
            - ~
            - Application\LandingBundle\Entity\Order
            - ~