<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYdw8i5k\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYdw8i5k/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYdw8i5k.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYdw8i5k\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYdw8i5k\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ydw8i5k',
    'container.build_id' => '6a530e64',
    'container.build_time' => 1524414920,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYdw8i5k');
