<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLy6je6b\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLy6je6b/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLy6je6b.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLy6je6b\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLy6je6b\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ly6je6b',
    'container.build_id' => '53c5d321',
    'container.build_time' => 1524322694,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLy6je6b');
