<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'assetic.filter.yui_css' shared service.

include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/FilterInterface.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/BaseProcessFilter.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/Yui/BaseCompressorFilter.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/Yui/CssCompressorFilter.php';

$this->services['assetic.filter.yui_css'] = $instance = new \Assetic\Filter\Yui\CssCompressorFilter(($this->targetDirs[3].'/app/Resources/java/yuicompressor-2.4.8.jar'), '/usr/bin/java');

$instance->setCharset('UTF-8');
$instance->setTimeout(NULL);
$instance->setStackSize(NULL);
$instance->setLineBreak(NULL);

return $instance;
