<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'assetic.asset_manager' shared service.

include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Factory/Loader/FormulaLoaderInterface.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Extension/Twig/TwigFormulaLoader.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Cache/ConfigCache.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Factory/Loader/CachedFormulaLoader.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Factory/Resource/ResourceInterface.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Factory/Resource/IteratorResourceInterface.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Factory/Resource/DirectoryResource.php';
include_once $this->targetDirs[3].'/vendor/symfony/assetic-bundle/Factory/Resource/DirectoryResource.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Factory/Resource/CoalescingDirectoryResource.php';
include_once $this->targetDirs[3].'/vendor/symfony/assetic-bundle/Factory/Resource/CoalescingDirectoryResource.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/AssetManager.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Factory/LazyAssetManager.php';

$this->services['assetic.asset_manager'] = $instance = new \Assetic\Factory\LazyAssetManager(${($_ = isset($this->services['assetic.asset_factory']) ? $this->services['assetic.asset_factory'] : $this->getAssetic_AssetFactoryService()) && false ?: '_'}, array('twig' => new \Assetic\Factory\Loader\CachedFormulaLoader(new \Assetic\Extension\Twig\TwigFormulaLoader(${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.assetic']) ? $this->services['monolog.logger.assetic'] : $this->load('getMonolog_Logger_AsseticService.php')) && false ?: '_'}), new \Assetic\Cache\ConfigCache(($this->targetDirs[0].'/assetic/config')), true)));

$a = ${($_ = isset($this->services['templating.loader']) ? $this->services['templating.loader'] : $this->load('getTemplating_LoaderService.php')) && false ?: '_'};

$instance->addResource(new \Symfony\Bundle\AsseticBundle\Factory\Resource\CoalescingDirectoryResource(array(0 => new \Symfony\Bundle\AsseticBundle\Factory\Resource\DirectoryResource($a, 'SiteBundle', ($this->targetDirs[3].'/app/Resources/SiteBundle/views'), '/\\.[^.]+\\.twig$/'), 1 => new \Symfony\Bundle\AsseticBundle\Factory\Resource\DirectoryResource($a, 'SiteBundle', ($this->targetDirs[3].'/src/SiteBundle/Resources/views'), '/\\.[^.]+\\.twig$/'))), 'twig');
$instance->addResource(new \Symfony\Bundle\AsseticBundle\Factory\Resource\CoalescingDirectoryResource(array(0 => new \Symfony\Bundle\AsseticBundle\Factory\Resource\DirectoryResource($a, 'GalleryBundle', ($this->targetDirs[3].'/app/Resources/GalleryBundle/views'), '/\\.[^.]+\\.twig$/'), 1 => new \Symfony\Bundle\AsseticBundle\Factory\Resource\DirectoryResource($a, 'GalleryBundle', ($this->targetDirs[3].'/src/GalleryBundle/Resources/views'), '/\\.[^.]+\\.twig$/'))), 'twig');
$instance->addResource(new \Symfony\Bundle\AsseticBundle\Factory\Resource\CoalescingDirectoryResource(array(0 => new \Symfony\Bundle\AsseticBundle\Factory\Resource\DirectoryResource($a, 'SonataAdminBundle', ($this->targetDirs[3].'/app/Resources/SonataAdminBundle/views'), '/\\.[^.]+\\.twig$/'), 1 => new \Symfony\Bundle\AsseticBundle\Factory\Resource\DirectoryResource($a, 'SonataAdminBundle', ($this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Resources/views'), '/\\.[^.]+\\.twig$/'))), 'twig');
$instance->addResource(new \Symfony\Bundle\AsseticBundle\Factory\Resource\CoalescingDirectoryResource(array(0 => new \Symfony\Bundle\AsseticBundle\Factory\Resource\DirectoryResource($a, 'LandingBundle', ($this->targetDirs[3].'/app/Resources/LandingBundle/views'), '/\\.[^.]+\\.twig$/'), 1 => new \Symfony\Bundle\AsseticBundle\Factory\Resource\DirectoryResource($a, 'LandingBundle', ($this->targetDirs[3].'/src/LandingBundle/Resources/views'), '/\\.[^.]+\\.twig$/'))), 'twig');
$instance->addResource(new \Symfony\Bundle\AsseticBundle\Factory\Resource\DirectoryResource($a, '', ($this->targetDirs[3].'/app/Resources/views'), '/\\.[^.]+\\.twig$/'), 'twig');

return $instance;
