<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sonata\MediaBundle\Command\FixMediaContextCommand' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/ContainerAwareCommand.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/media-bundle/src/Command/FixMediaContextCommand.php';

return $this->services['Sonata\MediaBundle\Command\FixMediaContextCommand'] = new \Sonata\MediaBundle\Command\FixMediaContextCommand();
