<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.media.adapter.image.imagick' shared service.

include_once $this->targetDirs[3].'/vendor/imagine/imagine/lib/Imagine/Imagick/Imagine.php';

return $this->services['sonata.media.adapter.image.imagick'] = new \Imagine\Imagick\Imagine();
