<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.media.resizer.square' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/media-bundle/src/Resizer/SquareResizer.php';

return $this->services['sonata.media.resizer.square'] = new \Sonata\MediaBundle\Resizer\SquareResizer(${($_ = isset($this->services['sonata.media.adapter.image.gd']) ? $this->services['sonata.media.adapter.image.gd'] : $this->services['sonata.media.adapter.image.gd'] = new \Imagine\Gd\Imagine()) && false ?: '_'}, 'inset', ${($_ = isset($this->services['sonata.media.metadata.proxy']) ? $this->services['sonata.media.metadata.proxy'] : $this->services['sonata.media.metadata.proxy'] = new \Sonata\MediaBundle\Metadata\ProxyMetadataBuilder($this)) && false ?: '_'});
