<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.media.doctrine.event_subscriber' shared service.

include_once $this->targetDirs[3].'/vendor/doctrine/common/lib/Doctrine/Common/EventSubscriber.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/media-bundle/src/Listener/BaseMediaEventSubscriber.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/media-bundle/src/Listener/ORM/MediaEventSubscriber.php';

return $this->services['sonata.media.doctrine.event_subscriber'] = new \Sonata\MediaBundle\Listener\ORM\MediaEventSubscriber($this);
