<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.media.form.type.media' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/media-bundle/src/Form/Type/MediaType.php';

$this->services['sonata.media.form.type.media'] = $instance = new \Sonata\MediaBundle\Form\Type\MediaType(${($_ = isset($this->services['sonata.media.pool']) ? $this->services['sonata.media.pool'] : $this->getSonata_Media_PoolService()) && false ?: '_'}, 'Application\\Sonata\\MediaBundle\\Entity\\Media');

$instance->setLogger(${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'});

return $instance;
