<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.command.init_acl' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/ContainerAwareCommand.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/Command/InitAclCommand.php';

$this->services['security.command.init_acl'] = $instance = new \Symfony\Bundle\SecurityBundle\Command\InitAclCommand(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->load('getDoctrine_Dbal_DefaultConnectionService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.acl.dbal.schema']) ? $this->services['security.acl.dbal.schema'] : $this->load('getSecurity_Acl_Dbal_SchemaService.php')) && false ?: '_'});

$instance->setName('init:acl');

return $instance;
