<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.media.adapter.service.s3' shared service.

return $this->services['sonata.media.adapter.service.s3'] = \Aws\S3\S3Client::factory(array());
