<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.user.form.gender_list' shared service.

@trigger_error('The "sonata.user.form.gender_list" service is deprecated since 4.x and will be removed in 5.0.', E_USER_DEPRECATED);

return $this->services['sonata.user.form.gender_list'] = new \Sonata\UserBundle\Form\Type\UserGenderListType('SiteBundle\\Entity\\User', 'getGenderList', 'Sonata\\UserBundle\\Form\\Type\\UserGenderListType');
